### ISSUE TITLE
unity play report: Start K4A cameras failed!

### ISSUE THREAD

**Issue by jimzou** [satoshi-maemoto/Azure-Kinect-Unity-Body-Tracker#2]
Thank you for your project, my unit test was successful, but the execution in unity always reported start K4A cameras failed!, tried SDK 1.1.0 BT 0.9.0, SDK 1.1.1 BT 0.9.1, all of these are errors, I don't know what the problem is.
ERR:
K4ABTException: Start K4A cameras failed!
AzureKinect.Unity.BodyTracker.AzureKinectBodyTracker.Start (System.UInt32 depthTextureId, System.UInt32 colorTextureId, System.UInt32 transformedDepthTextureId) (at Assets/K4AUnityBT/Scripts/AzureKinectBodyTracker.cs:121)
AzureKinect.Unity.BodyTracker.Sample.Controller+<Process>d__10.MoveNext () (at Assets/K4AUnityBT/Samples/Scripts/Controller.cs:55)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at D:/unity/Runtime/Export/Scripting/Coroutines.cs:17)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
AzureKinect.Unity.BodyTracker.Sample.Controller:Start() (at Assets/K4AUnityBT/Samples/Scripts/Controller.cs:35)

**Comment by satoshi-maemoto** [comment]
Thank you for your report.
This is my environment work fine.
depthengine_1_0.dll located to Unity project folder.

![image](https://user-images.githubusercontent.com/530182/63096808-d080f000-bfa9-11e9-8921-0dbdf46392a8.png)

and attribute of depthengine_1_0.dll

![image](https://user-images.githubusercontent.com/530182/63096892-08883300-bfaa-11e9-9cea-943de72fc7ca.png)

How your environment?

By the way, I tried play after remove the depthengine_1_0.dll then I got same error you reported.

**Comment by Chris45215** [comment]
Thanks, I ran into the same problem, and it was solved by putting those files in the project parent folder as you describe. It's tempting to put them in the Assets/K4AUnityBT subfolder. 

The speed after this update is much faster, and I can't thank you enough.

**Comment by satoshi-maemoto** [comment]
I'm testing AKBT SDK v0.9.1 now.
I must locate onnxruntime.dll into the Unity project folder to run.

**Comment by jimzou** [comment]
Thanks，it was solved
