### ISSUE TITLE
Memory leak about the newest version(Azure Kinect Body Tracking SDK v0.9.2)

### ISSUE THREAD

**Issue by maowu** [satoshi-maemoto/Azure-Kinect-Unity-Body-Tracker#20]
Hi, I am testing the newest version of K4AUnityBT example. The memory is constantly increasing while program running. 

I am try with: 
- Unity 2019.2.3f1
- Azure Kinect SDK v1.2.0
- Azure Kinect Body Tracking SDK 0.9.2

**Comment by satoshi-maemoto** [comment]
@maowu 
Thank you for your feedback!!
I will check ASAP.

**Comment by satoshi-maemoto** [comment]
Ohh.
![image](https://user-images.githubusercontent.com/530182/64145313-39de7b00-ce53-11e9-8793-e0584666d9b7.png)

**Comment by satoshi-maemoto** [comment]
Ohh
![image](https://user-images.githubusercontent.com/530182/64145431-ba04e080-ce53-11e9-992f-4bab16c6f585.png)

**Comment by satoshi-maemoto** [comment]
@maowu Problem resolved. Please get latest files from master branch.

**Comment by maowu** [comment]
> @maowu Problem resolved. Please get latest files from master branch.

Thank you, already test it.
