### ISSUE TITLE
Invert the y-axis in BodyVisualizer

### ISSUE THREAD

**Issue by Chris45215** [satoshi-maemoto/Azure-Kinect-Unity-Body-Tracker#3]
In the BodyVisualizer script, change line 47 to invert the Y axis. One easy way to do it is to change the line to:  
this.jointRenderers[i].transform.localPosition = new Vector3(body.skeleton.joints[i].position.x, body.skeleton.joints[i].position.y * -1, body.skeleton.joints[i].position.z) / 1000f;

Then in the Unity sample scene, you can remove the 180 degree rotations that are applied to the bodies. I suspect that the Azure Kinect uses a reversed Y axis because the origin point for images is the top-left corner and the Y axis points downwards, whereas 3D scenes have the origin point at the base and the Y axis points upwards - this causes the Y axis to be mirrored or inverted.

My project is in Unity 2019.1 at the moment, but I can get 2019.2 to create a fork of this repo and submit an update if that helps.

**Comment by satoshi-maemoto** [comment]
@Chris45215 Thank you for your suggestion! I also think it's more smarter than the current code.
I did in #6
