### ISSUE TITLE
HDRP project，k4abt flash off with：Error! Add capture to tracker process queue failed!

### ISSUE THREAD

**Issue by jimzou** [satoshi-maemoto/Azure-Kinect-Unity-Body-Tracker#31]
Thank you for work!
If project in HDRP mode，k4abt flash off with：Error! Add capture to tracker process queue failed!

**Comment by satoshi-maemoto** [comment]
Hi!
I tried upgrade the sample scene to the HDRP.
https://github.com/satoshi-maemoto/Azure-Kinect-Unity-Body-Tracker/tree/branches/%2331_hdrp
but, I have no error. works fine.
I guess related performance of GPU.
I'm using GTX-1070. did you?

**Comment by jimzou** [comment]
Thanks! There is no problem with your latest package, it may be my problem upgrading HDRP. I'm using GTX-1050i
