### ISSUE TITLE
DllNotFoundException: K4AUnityBTPlugin

### ISSUE THREAD

**Issue by Piler-Tam** [satoshi-maemoto/Azure-Kinect-Unity-Body-Tracker#34]
Branches before #32 works fine. 

Branch#32 and master branch log errors as below.

![log](https://user-images.githubusercontent.com/31006388/67351596-7ccdec80-f580-11e9-9d87-502537aa8ba5.PNG)

Finally, this plugin works well in the previous versions, great job!

**Comment by satoshi-maemoto** [comment]
@Piler-Tam Hi! thank you for your report.
The master branch works with Sensor SDK v1.3.0 and BT SDK v0.9.4.
What version do you using?

**Comment by Piler-Tam** [comment]
> @Piler-Tam Hi! thank you for your report.
> The master branch works with Sensor SDK v1.3.0 and BT SDK v0.9.4.
> What version do you using?

Thanks for your reply.
I am using Sensor SDK v1.3.0, BT SDK v0.9.4 and Unity 2019.2.5f1

**Comment by satoshi-maemoto** [comment]
@Piler-Tam 
Following are my environment which works fine. 
![image](https://user-images.githubusercontent.com/530182/67387344-ac591500-f5d1-11e9-931f-0ef52639b5e0.png)

![image](https://user-images.githubusercontent.com/530182/67387394-c266d580-f5d1-11e9-914f-b92cba234a99.png)

and dependencies of K4AUnityBTPlugin.dll.
![image](https://user-images.githubusercontent.com/530182/67387882-b0396700-f5d2-11e9-8b70-7d0c2cf57c59.png)

**Comment by Piler-Tam** [comment]
![1](https://user-images.githubusercontent.com/31006388/67538105-a158ce80-f710-11e9-8884-0ea26fabf53d.PNG)
![2](https://user-images.githubusercontent.com/31006388/67538106-a158ce80-f710-11e9-8e54-ee766100836f.PNG)

I have followed your environment but still the same situation.

I think K4ABT_SetDebugLogCallback(IntPtr callback) may be the reason

**Comment by satoshi-maemoto** [comment]
@Piler-Tam Are there some difference of K4AUnityBTPlugin.dll dependencies on your environment?
I'm using this tool.
https://lucasg.github.io/Dependencies/

**Comment by Piler-Tam** [comment]
@satoshi-maemoto 
This is the dependencies.
![d](https://user-images.githubusercontent.com/31006388/67738016-1ea17d80-fa48-11e9-8d17-5d2391bfefc9.PNG)

It seems no difference except you have one more VCRUNTIME140_1.dll

**Comment by satoshi-maemoto** [comment]
@Piler-Tam 
Sorry for late reply.
I saw similar error on the environment not mine.
So I tried to install the latest VisualC ++ runtime (vc_redist.x64.exe) and fixed the error.
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by Piler-Tam** [comment]
@satoshi-maemoto 
Yes. It works.Thanks anyway.
